### PR TITLE
Remove namespace

### PR DESCRIPTION
**Pull request by whites11**

### CODE REVIEW

**Review by calvix — APPROVED** [review]
weird but i assume you have a reason for doing this

**Comment by whites11** [comment]
> weird but i assume you have a reason for doing this

https://gigantic.slack.com/archives/C02FJACQ3D4/p1646727816792969?thread_ts=1646727120.152009&cid=C02FJACQ3D4

**Review by fiunchinho — APPROVED** [review]
I did not know this

**Review by ubergesundheit — APPROVED** [review]
LGTM

**Pull request merged**
